### ISSUE TITLE
脚本遇到需要点击OK的情况下无法继续

### ISSUE THREAD

**Issue by Fire1nRain** [Fire1nRain/MyNBA2K15-Automate#12]

**Comment by lowclood** [comment]
我看到你rc第34名了！你這樣一天跑了幾場阿?code release了嗎？
2014/12/30 下午9:34 於 "Junxiao Gao" <notifications@github.com> 寫道：

**Comment by lowclood** [comment]
恭喜囉 現在你已經跑到19名了耶，看樣子你的程式程式跑很穩，應該沒問題了！
2015/1/2 上午11:54 於 "Ivan Hung" <bfp339@gmail.com> 寫道：

**Comment by Fire1nRain** [comment]
@lowclood 才看到你两个礼拜前的消息，不知道为啥github不邮件通知了……最近在捣鼓后台运行版本，所以一直没更新，用了个第三方的后台扫图插件，效率比自带是版本快多了，就是准确度令人头痛。等今天回到家了我更新下代码吧

**Comment by Fire1nRain** [comment]
@lowclood 现在打四节比赛的话基本上45-50s一场，5节的话1分钟一场，出错也基本没了，就是貌似插件有bug还是怎么的，蓝屏了好几回……

**Comment by lowclood** [comment]
我看你rc衝很快很高啊，看起來很穩定
2015/1/17 下午6:51 於 "Junxiao Gao" <notifications@github.com> 寫道：

**Comment by Fire1nRain** [comment]
@lowclood也只有稳定这唯一一个优点了，速度上来说还是跑不过前五的那几个

**Comment by lowclood** [comment]
前五太扯 不過你的也要在網絡環境穩定下才跑的順利吧？看你的code似乎沒有特別針對網絡去設定
2015/1/17 下午7:33 於 "Junxiao Gao" <notifications@github.com> 寫道：

**Comment by Fire1nRain** [comment]
@lowclood 因为不需要针对网络设定啊，网络不好的时候他会转那个篮球，这时候脚本找不到任何特征图片，就会点击右下角一块基本上不会按到任何按钮的地方，然后进入下一次循环。如果一定时间内一直找不到，就会尝试退出到主界面然后重新登录啊
